apiVersion: numaplane.numaproj.io/v1alpha1
kind: NumaflowControllerRollout
metadata:
  name: numaflow-controller
  namespace: numaplane-e2e
spec:
  controller:
    # scenario: bump to "1.8.3" to start a Progressive controller upgrade
    version: "1.7.5"
